version: "3.8"
services:
  frontend:
    image: node:16-bullseye
    working_dir: /app
    build:
      context: ./nift
    tty: true
    volumes:
      - ./nift:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
  postgresql:
    build:
      context: ./docker/postgresql
    volumes:
      - ./docker/postgresql/database:/var/lib/postgresql/data
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
