version: 2.1

jobs:
  deploy:
    # set docker image
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0b:b9:7b:f7:29:31:bb:8b:a9:18:57:41:7b:f9:72:eb"
      - run:
          name: "Pull and deploy"
          command: "ssh -o StrictHostKeyChecking=no ${SSH_USER_NAME}@${SSH_HOST_NAME} \
            \"ssh ${REMOTE_HOST_NAME} \
            'cd ~/tools/NiFT && git pull origin release:release && bash deploy.sh'\""

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          context:
            - nift-settings
          filters:
            branches:
              only:
                - release
