name: Prettier

on: push

env:
  FILE_PATTERN: "src/**/*.{ts,tsx,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Linter Check
        run: |
          yarn install
          yarn run lint
        working-directory: ./frontend
